author: yanm1ng # ‰ΩúËÄÖ
description: yanm1ng's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 GitBook: https://www.gitbook.com/@raphaelli
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment or uyan

# comment: gitment

# gitment config
# gitment_owner: raphaelli
# gitment_repo: raphaelli.github.io
# gitment_oauth_id: 47f364add93b9bc398a3
# gitment_oauth_secret: 96f01843c18819503124e40afe1cdcbb87f772ee

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: https://ns96.com/2017/08/21/PostsDemo/banner.jpg
  avatar: https://avatars1.githubusercontent.com/u/9829111?s=460&v=4
  description: Never say neverüíª. Love 77 forever („ÄÇ„Éªœâ„Éª„ÄÇ)„Éé‚ù§!  
  weibo_username: microsoft96
  twitter_username: MagicEvolve
  github_username: raphaelli
  zhihu_username: raphael96
  douban_username: 71985573

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
